sudo: required
dist: xenial

env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - NUGET_XMLDOC_MODE=skip

script:
  - ./build.sh

after_success:
  - bash <(curl -s https://codecov.io/bash) -f "./artifacts/coverage.cobertura.xml" -F $TRAVIS_OS_NAME || echo "Codecov did not collect coverage reports"

addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8

branches:
  only:
    - master
    - deploy

cache:
  directories:
    - /home/travis/.nuget/packages

deploy:
  - provider: lambda
    function_name: "alexa-london-travel-dev"
    region: "eu-west-1"
    role: "arn:aws:iam::492538393790:role/lambda_basic_execution"
    runtime: "dotnetcore2.1"
    timeout: 10,
    zip: "./artifacts/publish"
    module_name: "LondonTravel.Skill::MartinCostello.LondonTravel.Skill.AlexaSkill"
    handler_name: "HandlerAsync"
    access_key_id:
      secure: "aJjugFDE24Z5UB/3PEGJEOlmpLFTUEQvtrczJiRRVBd1cG535MVmSm2GlVzVk1J96yqoVc8VqSEgWcdqlMcU4jupd6BxxFYDZE8k8hEQ9KmIFqG+VdBqn6SskadDVi/sihDakMvGVLi9koVOPfbYPoxQn+YOh3Ohu9RFbGKlUaX1/7s29VoBsX/e2iWvJQDVGqMWMg1hMtf91diOuxLbiUgsZWHQppm34UiM2oJBFHLuCjvSbtJMWJxEEULou9dgip1bCj5IxrpIM68E3Mn9ttK4ZotyL3LsgJYHp9P6KapzytKSa5eBoSXhJZx1FWMBSBW258uOtByARQyKBKrPg+csS7H8kFLNnaWLQhJqQGjU9eex6eVRDdeTcp4z5yfeGG803CrvWGcyHXANI/s1H0ktdzNK4T/SWEDh4oTgZzjaJdF15Upgw2GczO5TeO+9kbqc8cBHPHZmWp6q+bb6svvlX+EU3brBCcCIHDkwAp4Yv4rT/41ZKh0aZJ61/1Ulkb/xDcZh30kV8gc3dqnF6L8fhDXIfL1wMvw88lItiHiADcaqVV2Bb4OT4vP+cuSx7Ys7e7eyJn2y4qMqeCiFaGKqqYTbPG1gXJCLIhlqwLYJsf3yweTar8qqnrMhSJ5D6lRp9Eh2xoAk60jIBJgCH/oRjp0aErxJ4/iwxZcNx0Q="
    secret_access_key:
      secure: "AAlbSXUSgawEkKHnDjk5tA8NsVkd24ttpVXAAGETsf4aDbDSCWS/eV8cEQZkCNE2H2W7TG44qHvBGIXZLRO8VC9VXluX4kg2d1FMJC6NyHQNqU/PWV9eoIUHqxfe1MfJzXRosqQuYE5SWemNkONyh+/dw/FPMUjtNUMfilGVQLhK5xpkJvmJLvaUNilEd1M9DHWG/3xeY4WnXaauoaVL5WAu9cpGgMASKKaBP+Vx+4N7SGY/QepAS7nT8grPkDX1SlnQXCqXIBZli9m9gEUclQglEWfNwmCT8aAd+G4g3iEs1v8gEmTxPMrdeCvU4VHhed8kfjwFDzBMmgWNZXQFAdEPgl5j6aWN+YNwFyOFU00U5FzOb+iRc9dswrYC/tnNTG1JLCw/Zhk8PDE44/9ZA0B2ix31RvxLKlwWEn7qecx7+ODqmYLeZ2uDwfmn9FVpvGkTx8cy4hz92kDUHiODBNAO13kNhmkvHphLXTAmjevTePyOxUybDmHm27uRj1Q5gTG7en0nekJb8CMPIwnFD+j+OMG5HRJ9T95DTw3At3OMHOPUHprSmLBBFlI2qjbMvkKmduapyh2h5au0kZS7q+tQkcW5jvRFeGox//wshtILgOZmC0cjc5w9KTiavO3ItFcd5o69f1Hcmy/IuQyN3YTXWYByd0ircTBXUBtRLhE="
    on:
      branch: master
  - provider: lambda
    function_name: "alexa-london-travel"
    region: "eu-west-1"
    role: "arn:aws:iam::492538393790:role/lambda_basic_execution"
    runtime: "dotnetcore2.1"
    timeout: 10,
    zip: "./artifacts/publish"
    module_name: "LondonTravel.Skill::MartinCostello.LondonTravel.Skill.AlexaSkill"
    handler_name: "HandlerAsync"
    access_key_id:
      secure: "aJjugFDE24Z5UB/3PEGJEOlmpLFTUEQvtrczJiRRVBd1cG535MVmSm2GlVzVk1J96yqoVc8VqSEgWcdqlMcU4jupd6BxxFYDZE8k8hEQ9KmIFqG+VdBqn6SskadDVi/sihDakMvGVLi9koVOPfbYPoxQn+YOh3Ohu9RFbGKlUaX1/7s29VoBsX/e2iWvJQDVGqMWMg1hMtf91diOuxLbiUgsZWHQppm34UiM2oJBFHLuCjvSbtJMWJxEEULou9dgip1bCj5IxrpIM68E3Mn9ttK4ZotyL3LsgJYHp9P6KapzytKSa5eBoSXhJZx1FWMBSBW258uOtByARQyKBKrPg+csS7H8kFLNnaWLQhJqQGjU9eex6eVRDdeTcp4z5yfeGG803CrvWGcyHXANI/s1H0ktdzNK4T/SWEDh4oTgZzjaJdF15Upgw2GczO5TeO+9kbqc8cBHPHZmWp6q+bb6svvlX+EU3brBCcCIHDkwAp4Yv4rT/41ZKh0aZJ61/1Ulkb/xDcZh30kV8gc3dqnF6L8fhDXIfL1wMvw88lItiHiADcaqVV2Bb4OT4vP+cuSx7Ys7e7eyJn2y4qMqeCiFaGKqqYTbPG1gXJCLIhlqwLYJsf3yweTar8qqnrMhSJ5D6lRp9Eh2xoAk60jIBJgCH/oRjp0aErxJ4/iwxZcNx0Q="
    secret_access_key:
      secure: "AAlbSXUSgawEkKHnDjk5tA8NsVkd24ttpVXAAGETsf4aDbDSCWS/eV8cEQZkCNE2H2W7TG44qHvBGIXZLRO8VC9VXluX4kg2d1FMJC6NyHQNqU/PWV9eoIUHqxfe1MfJzXRosqQuYE5SWemNkONyh+/dw/FPMUjtNUMfilGVQLhK5xpkJvmJLvaUNilEd1M9DHWG/3xeY4WnXaauoaVL5WAu9cpGgMASKKaBP+Vx+4N7SGY/QepAS7nT8grPkDX1SlnQXCqXIBZli9m9gEUclQglEWfNwmCT8aAd+G4g3iEs1v8gEmTxPMrdeCvU4VHhed8kfjwFDzBMmgWNZXQFAdEPgl5j6aWN+YNwFyOFU00U5FzOb+iRc9dswrYC/tnNTG1JLCw/Zhk8PDE44/9ZA0B2ix31RvxLKlwWEn7qecx7+ODqmYLeZ2uDwfmn9FVpvGkTx8cy4hz92kDUHiODBNAO13kNhmkvHphLXTAmjevTePyOxUybDmHm27uRj1Q5gTG7en0nekJb8CMPIwnFD+j+OMG5HRJ9T95DTw3At3OMHOPUHprSmLBBFlI2qjbMvkKmduapyh2h5au0kZS7q+tQkcW5jvRFeGox//wshtILgOZmC0cjc5w9KTiavO3ItFcd5o69f1Hcmy/IuQyN3YTXWYByd0ircTBXUBtRLhE="
    on:
      branch: deploy
